[production]
production-server ansible_host=production-server ansible_user=root ansible_ssh_private_key_file=~/.ssh/prod_key

[production:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
app_port=8080
app_user=root
app_dir=/opt/petclinic